version: '3.8'

services:
  go_api:
    build:
      context: .
      dockerfile: Dockerfile.go
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - typescript_crawler

  typescript_crawler:
    build:
      context: ./typescript_crawler
      dockerfile: Dockerfile.ts
    ports:
      - "3000:3000"
