version: '3.8'

services:
  go_api:
    build:
      context: .
      dockerfile: Dockerfile.go
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      # Usando ${PWD} para referenciar o caminho relativo ao diretório atual
      - ${PWD}/internal/pdf_normas:/app/internal/pdf_normas
    depends_on:
      - typescript_crawler

  typescript_crawler:
    build:
      context: ./internal/automation
      dockerfile: Dockerfile.ts
    ports:
      - "3000:3000"
    volumes:
      # Usando ${PWD} para referenciar o caminho relativo ao diretório atual
      - ${PWD}/internal/pdf_normas:/app/internal/pdf_normas
